packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  typescript: 5.8.3

registry:
  default: https://registry.npmmirror.com/

preferWorkspacePackages: true
sharedWorkspaceLockfile: true
allowBuilds:
  '@nestjs/core': true
  esbuild: false
