packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  typescript: 5.8.3

registry:
  default: https://registry.npmmirror.com/

preferWorkspacePackages: true
sharedWorkspaceLockfile: true
overrides:
  cors: 2.8.5
  '@nestjs/platform-express>cors': 2.8.5
allowBuilds:
  '@nestjs/core': true
  better-sqlite3: true
  esbuild: false
